title: "Living Document"
author: Moritz Eckmann, Permallim Spahija, Jonas Bruncks
  

date: "r format(Sys.Date(), '%B %d, %Y')"
format:
  html:
    toc: true
    toc-depth: 3
  pdf:
    documentclass: article
    papersize: a4
    fontsize: 12pt
bibliography: references.bib
csl: apa-7.csl
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE


_quarto/
.quarto/
*.html
*.pdf


### Code of Conduct

#### Umgang mit Feedback, unterschiedlichen Perspektiven und Meinungsverschiedenheiten

#### Faire Aufteilung der Arbeitslast

#### Verhalten in Bezug auf vereinbarte und verpflichtende Termine

#### Einhaltung der wissenschaftlichen Integrität (siehe vorangehende Folien)

#### Verpflichtung zum Schutz von Daten und zur Wahrung ihrer Vertraulichkeit

#### Nutzung und Kennzeichnung von AI Tools (z.B. ChatGPT)


# 1. Einletung

# 2. Literaturübersicht

Die drei Studien NEBULA zur KI-Erkennung von Fake News, Forschung zu visueller Desinformation und die Übersichtsstudie zu Gesundheits-Fake News zeigen grundsätzlich alle das gleiche Problem. Falschinformationen verbreiten sich heutzutage viel schneller und weiter als korrekte Informationen. Das liegt daran, dass emotionale Inhalte, Social Media-Algorithmen und geschlossene Meinungsblasen die Verbreitung fördern und vor allem keine anderen Meinungen und Informationen zulassen.

Das NEBULA Projekt entwickelt zwar gute technische Lösungen zum Erkennen von Falschinformationen, da die Menge an Mis- bzw. Desinformationen aber so groß ist, reicht die Technik noch nicht aus um die Masse an den fragwürdigen Informationen als gesichert falsch einzustufen. Betroffene können sowohl Einzelpersonen als auch die breite Bevölkerung sein. Dadurch kann der Ruf von einzelnen Menschen zu Unrecht geschädigt werden oder eine allgemeine Unsicherheit entstehen, die unter anderem auch die Demokratie gefährden kann. Die Forschung zu Bildern und Videos zeigt in erster Linie ein Problem: So genannte Deepfakes und Cheapfakes. Videos mit Inhalten, die so nie geschehen sind, oder von Personen durchgeführt werden, die in der Realität nicht beteiligte waren. Diese Art von Fehlinformationen wirken durch die schnelle Verbreitung in den sozialen Medien sowie dem visuellen Erlebnis stärker als reine Textnachrichten und umgehen die kritische Filter. Genau wie in der Gesundheitsstudie wird deutlich, dass persönliche Geschichten und Verschwörungstheorien sich besonders gut in sozialen Medien verbreiten. Was können wir dagegen tun? Wir brauchen mehrere Ansätze gleichzeitig. Auf technischer Ebene zum Beispiel Tools wie NEBULA. Diese Art von Werkzeugen können Plattformen helfen Quellen besser zu kennzeichnen und fragwürdige Themen bzw. Informationen zu kennzeichnen. Auf psychologischer Ebene ist es wichtig Menschen zu zeigen, wie Manipulation funktioniert und wie man sich davor schützen kann. Der kritische Blick auf neue Informationen kann oft schon stutzig machen und die Verbreitung eindämmen. Die politische Aufgabe sollte eine stärkere Regulation der sozialen Medien sowie eine verbreitete Aufklärung über Mis- und Fehlinformationen sein. Noch offen sind die Langfristige Wirkung der Maßnahmen, die Verbindung mit den jeweiligen Zielgruppen und die Unterscheidung zwischen Textwarnungen und visuellen Hinweisen. Das Wichtigste ist, dass technische Lösungen, psychologische Ansätze und politische Regulierung in Zukunft kombiniert werden können. Zum Beispiel könnten KI-Tools nicht nur warnen, sondern mit Erklärvideos direkt wichtiges Informationen zu diesem Thema vermitteln.


# 3. Methode

Qualitative Methode:

Für die Forschungsfrage wurde ein qualitativer Forschungsansatz gewählt, da dieser am besten geeignet ist, um subjektiven Erfahrungen, Einstellungen und Bedürfnisse der Nutzer im Zusammenhang mit Künstlicher Intelligenz und Misinformation zu erfassen. Die Forschungsfrage zielt nicht darauf ab, statistisch repräsentative Aussagen zu treffen oder Korrelationen von Daten zu messen, sondern möchte ein tiefgehendes Verständnis dafür entwickeln, wie Individuen KI-Tools im Kontext von Desinformation wahrnehmen und welche Erwartungen sie an solche Systeme haben. 
Qualitative Methoden ermöglichen es unerwartete Perspektiven zu entdecken, vor allem im Kontext eines dynamischen Dialoges mit halbstrukturierten Leitfaden.

Datenerhebung:

Stichprobe: Es wurden zwei Personen gewählt.

Rekrutierung: Die Teilnehmer wurden über Uni-Netzwerke rekrutiert.

Interviewansatz: Es wurden halbstrukturierte Leitfadeninterviews durchgeführt, die eine dynamischen Dialog erlauben, aber Zentrale Themen (KI-Nutzung, Misinformation) abdecken. 

Aufnahme und Transkription: Die Interviews wurden persönlich geführt und aufgezeichnet, anschließend wortwörtlich transkribiert und anonymisiert, um eine detaillierte Analyse zu ermöglichen.

Quantitative Methode:

Die Datenerhebung für die Studie erfolgte, indem wir mit einem Einführungstext inklusive der wichtigsten Informationen rund um die Studie begonnen haben. In diesem gaben wir das Thema bzw. den Rahmen der Studie bekannt und haben die Teilnahmebedingungen aufgelistet. Zu den Teilnahmebedingungen gehört die Volljährigkeit, die Verfügung über ein Tablet oder PC sowie gute deutsch Kenntnisse. Danach überlegten wir uns, wie wir an möglichst viele Teilnehmer aus verschiedenen Altersklassen herankommen. Wir brauchten eine Plattform mit vielen Nutzer*innen und einem durchmischten Alter und kamen auf Reddit. Dort posteten wir unseren Info Text und den Link zur Studie. Abgesehen davon haben wir den Rekrutierungstext samt Link in das Asta-Forum gepostet.
Die Erhebung besteht aus fünf nacheinander ablaufenden Schritten. Beginnend mit dem Pre-Test-Fragebogen folgt die Klassifizierung von Zehn Posts ohne KI, ein Post-Baseline-Fragebogen, die Klassifizierung von Zehn Posts mit KI und einem Post-Test-Fragebogen.
Die Studie kann nur mit der Einwilligung der Datenschutzerklärung starten und befasst sich zunächst mit Probandeninformationen und einer Pre-test-Survey zu dem aktuellen Stand zum Thema KI-Nutzung sowie der Affinität für technologische Interaktion (Diagramm, Textfeld 3-6). Die passende Skala ist im single choice stil gehalten und stellt die Proban*innen vor die Aufgabe den Grad der Zustimmung zum Umgang mit technischen Systemen anzugeben (Quelle: Interaktionsbezogene Technik-Affinität: https://www.researchgate.net/publication/318745431_Assessing_Affinity_for_Technology_Interaction_-_The_Affinity_for_Technology_Interaction_ATI_Scale_Scale_Description_-_English_and_German_Scale_Version ). Anschließend wird ein Tutorial durchgeführt, um die Proband*innen auf die Studie vorzubereiten (Diagramm, Textfeld 7-8,). Die Durchführung der Studie beinhaltet die Einschätzung, ob vorgegebene Posts auf social Media der Wahrheit entsprechen, oder es sich um eine Misinformation handelt. Die Proband*innen sollen Zehn Posts ohne KI Unterstützung und Zehn Posts mit KI Unterstützung bewerten und dabei auf einen Button klicken, wenn ein Lämpchen von blau zu rot wechselt. (Diagramm, Textfeld 9-13). Danach sollen die Teilnehmer*innen in einer Post-Test-Survey die Arbeitsbelastung der Studie angeben, indem in einer passenden Ansicht zwischen unterfordernd, optimal und überfordernd gewählt werden kann (Quelle: Subjektiver Workload Baseline: https://www.researchgate.net/publication/377851950_DLR_Workload_Assessment_Tool_DLR-_WAT_-Official_English_Version?channel=doi&linkId=65bb62e634bbff5ba7ddea7a&showFulltext=true ) und der Eindruck des Systems mit dem die Studie arbeitet soll bewertet werden. (Diagramm, Textfeld 14-19). Bei der Bewertung geht es unter anderem um die Nutzbarkeit und um die Effektivität des Systems. Die Skala dazu fordert die Proband*innen dazu auf Fragen zur Usability zwischen Eins und Fünf zu beantworten, während die Eins für zutreffend und die Fünf für nicht zutreffend steht (Quelle: Usability: https://www.researchgate.net/publication/228593520_SUS_A_quick_and_dirty_usability_scale ). Des weiteren behandelt eine Skala das Thema „subjektives Informationsbewusstsein“ und es werden single choice Antworten in Sechs Stufen von „voll unzutreffend“ bis „voll zutreffend“ zu mehreren Fragen erwartet (Quelle: Subjektives Informationsverarbeitungsbewusstsein:
https://www.researchgate.net/publication/353288593_Subjective_Information_Processing_Awareness_Scale_SIPAS ). Zuletzt kommt ein Debriefing und den Teilnehmer*innen wird veranschaulicht, welche Posts Falschinformationen waren und welche nicht. Es wird zudem bei jedem Post gezeigt für welche Antwort sich die Teilnehmer*innen entschieden haben und, ob mit oder ohne KI Unterstützung gearbeitet wurde (Diagramm, Textfeld 20).
Wir planen zur Analyse einen t-Test und ein Korrelationstest zu vollziehen. Eine Möglichkeit für einen t-Test wäre, die Proband*innen in zwei Altersklassen zu teilen und zu untersuchen, welche Altersklasse eher der KI vertraut und wie die beiden Klassen auch ohne KI antworten. Ein Korrelationstest besteht aus einer unabhängigen Variable (UV) und einer abhängigen Variable (AV). Eine Möglichkeit wäre, so den Zusammenhang zwischen dem Alter der Proband*innen und den gegebenen Antworten zu den social Media Posts herzustellen. Außerdem könnte ebenfalls der Zusammenhang zwischen Alter und Verlass auf KI Unterstützung analysiert werden. 


# 4. Ergebnisse

Qualitative Ergebnisse:

Wir als Gruppe B2 der SMNF haben zwei Personen getrennt voneinander zum Thema KI zur Erkennung von Misinformationen auf sozialen Medien interviewt. Beide Interviews wurden jeweils transkribiert und thematisch analysiert. Dabei haben wir vier Themen herausfiltern und diese durch Textstellen und Codes unterstreichen können.
Die zunächst genannten Themen haben sich aus unserer Arbeit ergeben. Das erste Thema ist die KI-Nutzung im Alltag. Beide Personen gaben im Interview an, mit schon mindestens einer KI gearbeitet zu haben und sie unter anderem für Uni Zwecke genutzt zu haben. (B2_2 Z. 5-8 oder Tabelle Spalte 3): "Ja also ich glaube, ich habe KIs eigentlich schon in verschiedenen Bereichen benutzt, wahrscheinlich am meisten so in Form von Chatbots, aber ich kann mich auch erinnern KIs zur Bildgenerierung zum Beispiel benutzt zu haben oder in verschiedenen Bereichen hat man das ja auf jeden Fall schon mal gesehen."

Das zweite Thema handelt von dem Ungang mit Misinformation. Interessant war, dass beide Personen das Thema Misinformationen als erstes mit Wahlkämpfen in Verbindung gebracht haben. Die Rede war von unpräzisen und nicht wahren Informationen. Als Beispiel: B2_2: Z. 34-38) oder Tabelle Spalte 5: "Also das kriegt man schon durchaus mal mit, dass irgendwo, ob jetzt gezielt oder nicht, falsche InformaLonen verbreitet werden. Vor allem natürlich, wenn es irgendwie um politische Dinge geht, aber auch bei allen möglichen Sachen kann es schon sein, kriegt man schon mal mit, dass die Sachen nicht ganz stimmen oder unpräzise sind."
Daraus lässt sich schließen, dass eine Unterstützung zur Erkennung von Misinformationen vor allem, im politischen Kontext durchaus interessant sein könnte.

Das dritte Thema ist die KI als Lösung gegen Misinformation. Es hat sich interessanterweise schnell herausgestellt, dass beide Personen häufiger mit falschen Angaben durch künstliche Intelligenz Erfahrungen gemacht haben. Das Thema Fehler durch KI wird als normal und alltäglich angesehen. Zum Beispiel zu sehen bei B2_2: Z. 48-54) oder Tabelle Spalte 7: "Also KIs, wie man ja auch oft merkt, haben auch nicht nur richLge Informationen und dadurch könnte es dann auch entstehen, wenn vor allem eine gewisse Information irgendwie in der KI falsch aufgenommen wird, dass dann diese Beiträge gezielt als falsch gezeigt werden oder generell dadurch dann teilweise Informationen als falsch angezeigt werden, die es eigentlich nicht sind und so auch noch mehr falsche Informationen verbreitet werden." Das zeigt, dass die KI´s noch am Anfang stehen und verdeutlicht, dass die Realität von einem KI System zur Erkennung von Misinformation noch entfernt liegt. Jedoch, gaben beide an, sich vorstellen zu können, dass eine KI bei dem herausfiltern von Misinformation nützlich sein kann.

Das vierte Thema geht um die Anforderungen an ein KI System zur Erkennung von Misinformation. Zu dem Thema erwähnten die Personen, dass Transparenz sowie eine gute usability essenziell sei. (B2_1 Z. 62 oder Tabelle Spalte 8): "Es sollte leicht bedienbar sein, damit es alle verstehen." Und (B2_2 Z. 148-152 oder Tabelle Spalte 9:) "Ja genau, Transparenz bei KI ist ja schwierig, weil man nicht genau
sagen kann, was in dem System passiert. Was man sicher machen kann, ist halt, dass die KI immer Gründe angibt, weshalb es das denkt(…)."
Außerdem sprachen beid evon der Wichtigkeit, einen unabhängigen Betreiber für ein solches Sytem zu engagieren, um zu gewährleisten, dass keine eigennützigen Interessen verfolgt werden.


Abschließend lässt sich sagen, dass die geführten Interviews interessanterweise sowohl durch ähnliche als auch verschiedene Erfahrungen und Ansichten/Ideen der teilnehmenden Personen geprägt wurden.



# 5. Diskussion
